name: Python App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      S3_ATD_API: ${{ secrets.S3_ATD_API }}

    steps:
      - name: Debug secrets (Optional, don't do this for real secrets)
        run: echo "Secrets injected!"
